name: C++ Build and Tests

on:
  push:
    branches:
      - main
      - feature/member-a
      - feature/member-b
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Show compiler version
        run: g++ --version

      - name: Build application
        run: |
          g++ -std=c++17 -Wall -Wextra -Wpedantic -I include \
            src/main.cpp \
            src/core/Utils.cpp \
            src/core/FileIO.cpp \
            src/model/Maze.cpp \
            src/generator/DfsGenerator.cpp \
            src/solver/Solver.cpp \
            src/solver/AStar.cpp \
            -o maze_app

      - name: Build and run solver tests
        run: |
          g++ -std=c++17 -Wall -Wextra -Wpedantic -I include \
            tests/test_solver.cpp \
            src/solver/Solver.cpp \
            src/solver/AStar.cpp \
            -o test_solver
          ./test_solver

      - name: Build and run project tests
        run: |
          g++ -std=c++17 -Wall -Wextra -Wpedantic -I include \
            tests/test_project.cpp \
            src/core/Utils.cpp \
            src/core/FileIO.cpp \
            src/model/Maze.cpp \
            src/generator/DfsGenerator.cpp \
            src/solver/Solver.cpp \
            -o test_project
          ./test_project
